=== Rodez-IUT/dut-info2-filmprovider-BeJulien/Part1-XML-DTD/resources/XML2/Librairie.dtd
<!ELEMENT librairie (entete, livre+)>

<!ENTITY copyright "&copy;Librairie &amp; Internet 2020">

<!ENTITY % texte_mele "(#PCDATA | strong | em | img)*">
<!ELEMENT strong (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT img EMPTY>
<!ATTLIST img src   CDATA #REQUIRED
          title CDATA #IMPLIED
>

<!ENTITY % personne "(nom, prenom?)">
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>

<!ELEMENT entete %texte_mele;>

<!ELEMENT livre (titre, auteurs, description, prix)>
<!ATTLIST livre isbn ID #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT description %texte_mele;>
<!ELEMENT prix EMPTY>
<!ATTLIST prix valeur CDATA #REQUIRED
               devise ("euro" | "livre" | "dollar") "euro" #IMPLIED
               type   ("HT" | "TCC") "HT" #IMPLIED
               tva    "5.5" #FIXED
>

<!ELEMENT auteurs (auteur+ | collectif)>
<!ELEMENT auteur %personne;>
<!ELEMENT texte (#PCDATA)>

<!ELEMENT collectif (direction, membres)>
<!ELEMENT direction (auteur)>
<!ELEMENT membres (#PCDATA)>

=== Rodez-IUT/dut-info2-filmprovider-BeJulien/Part1-XML-DTD/resources/XML2/Librairie.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd">
<librairie>
    <entete>Ceci est l'entÃªte de la librairie</entete>
    <livre isbn="27877877979-5487">
        <titre>Le jardinage</titre>
        <auteurs>
            <auteur>
                <nom>Dujardin</nom>
                <prenom>Jean</prenom>
            </auteur>
            <auteur>
                <nom>Dupond</nom>
            </auteur>
            <auteur>
                <nom>Francis</nom>
                <prenom>Delamote</prenom>
            </auteur>
        </auteurs>
        <description>Le premier livre qui parle vraiment de jardinage</description>
        <prix devise="euro" type="TCC">10</prix>
    </livre>
    <livre isbn="27717877979-5487">
        <titre>Le grand tour du monde</titre>
        <auteurs>
            <collectif>
                <direction>
                    <auteur>
                        <nom>Olivier</nom>
                        <prenom>Laplace</prenom>
                    </auteur>
                </direction>
                <membres>
                    Patrice - Patricia
                </membres>
            </collectif>
        </auteurs>
        <description>Le tour du monde vu par Olivier</description>
        <prix devise="livre" type="HT">21</prix>
    </livre>
</librairie>
